apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: details
  description: Bookinfo details service (Ruby) — book metadata such as author, year and ISBN
  annotations:
    github.com/project-slug: wasp-foundry/details
    backstage.io/kubernetes-id: details
  tags:
    - ruby
spec:
  type: service
  lifecycle: experimental
  owner: group:default/team-beta
  system: bookinfo
  providesApis:
    - details-api
  dependsOn:
    - resource:default/development
    - resource:default/production
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: details-api
  description: Book details by product id
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/team-beta
  system: bookinfo
  definition:
    $text: ./openapi.yaml
